---
kind: pipeline
name: oauth-sdk-pipeline

steps:
  - name: "unit, build, package"
    image: openjdk:8-jdk-stretch
    commands:
      - ./gradlew test
      - ./gradlew build
      - ./gradlew shadowJar