---
kind: pipeline
name: oauth-sdk-pipeline

steps:
  - name: "unit, build, package"
    image: davidiamyou/open-jdk-8:latest
    commands:
      - ./gradlew test
      - ./gradlew build
      - ./gradlew shadowJar